-- MySQL Script generated by MySQL Workbench
-- 2018年06月22日 星期五 16时42分12秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zhaopin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zhaopin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zhaopin` DEFAULT CHARACTER SET utf8 ;
USE `zhaopin` ;

-- -----------------------------------------------------
-- Table `zhaopin`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`positions` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`positions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `sort` SMALLINT NOT NULL DEFAULT 0,
  `keywords` VARCHAR(245) NOT NULL DEFAULT '',
  `room_and_board` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '管吃管住3、管吃1、管住2、不包0',
  `number` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '预招人数',
  `content` TEXT NOT NULL COMMENT '职位详情',
  `benefit` VARCHAR(245) NOT NULL DEFAULT '' COMMENT '福利待遇',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '职位';


-- -----------------------------------------------------
-- Table `zhaopin`.`districts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`districts` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`districts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT NOT NULL DEFAULT 0,
  `parent_id` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `parent_id` (`parent_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '地区';


-- -----------------------------------------------------
-- Table `zhaopin`.`company_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`company_categories` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`company_categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '行业';


-- -----------------------------------------------------
-- Table `zhaopin`.`company_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`company_status` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`company_status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '公司状态';


-- -----------------------------------------------------
-- Table `zhaopin`.`company_size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`company_size` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`company_size` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `remark` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `sort` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '企业规模';


-- -----------------------------------------------------
-- Table `zhaopin`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`companies` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`companies` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `logo` VARCHAR(245) NOT NULL DEFAULT '',
  `number` VARCHAR(245) NOT NULL DEFAULT '' COMMENT '企业人数',
  `profile` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '公司简介',
  `phone` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '商务电话',
  `wechat` VARCHAR(45) NOT NULL DEFAULT '',
  `qq` VARCHAR(45) NOT NULL DEFAULT '',
  `company_category_id` INT UNSIGNED NOT NULL COMMENT '行业id',
  `company_status_id` INT UNSIGNED NOT NULL,
  `company_size_id` INT UNSIGNED NOT NULL,
  `imgs` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '图集地址',
  `sort` SMALLINT NOT NULL DEFAULT 0,
  `remark` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `district_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `company_category_id` (`company_category_id` ASC),
  INDEX `company_status_id` (`company_status_id` ASC),
  INDEX `company_size_id` (`company_size_id` ASC),
  INDEX `district_id` (`district_id` ASC),
  CONSTRAINT `category_id`
    FOREIGN KEY (`company_category_id`)
    REFERENCES `zhaopin`.`company_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `company_status_id`
    FOREIGN KEY (`company_status_id`)
    REFERENCES `zhaopin`.`company_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `company_size_id`
    FOREIGN KEY (`company_size_id`)
    REFERENCES `zhaopin`.`company_size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `district_id`
    FOREIGN KEY (`district_id`)
    REFERENCES `zhaopin`.`districts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '企业';


-- -----------------------------------------------------
-- Table `zhaopin`.`salaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`salaries` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`salaries` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `sort` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '工资';


-- -----------------------------------------------------
-- Table `zhaopin`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`users` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `sort` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zhaopin`.`resumes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`resumes` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`resumes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '目前状态：在职1/离职0',
  `remark` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `sort` SMALLINT NOT NULL DEFAULT 0,
  `worked_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '参加工作时间',
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `fk_resumes_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zhaopin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '简历';


-- -----------------------------------------------------
-- Table `zhaopin`.`intentions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`intentions` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`intentions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `sort` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '求职意向';


-- -----------------------------------------------------
-- Table `zhaopin`.`experiences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`experiences` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`experiences` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `sort` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '工作经历';


-- -----------------------------------------------------
-- Table `zhaopin`.`credits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`credits` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`credits` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `sort` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '积分';


-- -----------------------------------------------------
-- Table `zhaopin`.`invites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`invites` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`invites` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `sort` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '邀请';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
