-- MySQL Script generated by MySQL Workbench
-- 2018年06月29日 星期五 15时40分07秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zhaopin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zhaopin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zhaopin` DEFAULT CHARACTER SET utf8mb4 ;
USE `zhaopin` ;

-- -----------------------------------------------------
-- Table `zhaopin`.`admin_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`admin_menu` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`admin_menu` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` INT(11) NOT NULL DEFAULT '0',
  `order` INT(11) NOT NULL DEFAULT '0',
  `title` VARCHAR(50) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `icon` VARCHAR(50) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `uri` VARCHAR(50) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36;


-- -----------------------------------------------------
-- Table `zhaopin`.`admin_operation_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`admin_operation_log` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`admin_operation_log` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `path` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `method` VARCHAR(10) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `ip` VARCHAR(15) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `input` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `admin_operation_log_user_id_index` USING BTREE (`user_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2932;


-- -----------------------------------------------------
-- Table `zhaopin`.`admin_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`admin_permissions` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`admin_permissions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `slug` VARCHAR(50) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `http_method` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `http_path` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `admin_permissions_name_unique` USING BTREE (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7;


-- -----------------------------------------------------
-- Table `zhaopin`.`admin_role_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`admin_role_menu` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`admin_role_menu` (
  `role_id` INT(11) NOT NULL,
  `menu_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `admin_role_menu_role_id_menu_id_index` USING BTREE (`role_id` ASC, `menu_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhaopin`.`admin_role_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`admin_role_permissions` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`admin_role_permissions` (
  `role_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `admin_role_permissions_role_id_permission_id_index` USING BTREE (`role_id` ASC, `permission_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhaopin`.`admin_role_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`admin_role_users` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`admin_role_users` (
  `role_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `admin_role_users_role_id_user_id_index` USING BTREE (`role_id` ASC, `user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhaopin`.`admin_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`admin_roles` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`admin_roles` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `slug` VARCHAR(50) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `admin_roles_name_unique` USING BTREE (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2;


-- -----------------------------------------------------
-- Table `zhaopin`.`admin_user_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`admin_user_permissions` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`admin_user_permissions` (
  `user_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `admin_user_permissions_user_id_permission_id_index` USING BTREE (`user_id` ASC, `permission_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhaopin`.`admin_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`admin_users` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`admin_users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(190) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `password` VARCHAR(60) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `name` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `avatar` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `admin_users_username_unique` USING BTREE (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3;


-- -----------------------------------------------------
-- Table `zhaopin`.`company_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`company_categories` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`company_categories` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = '行业';


-- -----------------------------------------------------
-- Table `zhaopin`.`company_size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`company_size` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`company_size` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `sort` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `min` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `max` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COMMENT = '企业规模';


-- -----------------------------------------------------
-- Table `zhaopin`.`company_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`company_status` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`company_status` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = '公司状态';


-- -----------------------------------------------------
-- Table `zhaopin`.`districts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`districts` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`districts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  `parent_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `parent_id` (`parent_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COMMENT = '地区';


-- -----------------------------------------------------
-- Table `zhaopin`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`companies` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`companies` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `logo` VARCHAR(245) NOT NULL DEFAULT '',
  `number` VARCHAR(245) NOT NULL DEFAULT '' COMMENT '企业人数',
  `profile` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '公司简介',
  `phone` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '商务电话',
  `wechat` VARCHAR(45) NOT NULL DEFAULT '',
  `qq` VARCHAR(45) NOT NULL DEFAULT '',
  `company_category_id` INT(10) UNSIGNED NOT NULL COMMENT '行业id',
  `company_status_id` INT(10) UNSIGNED NOT NULL,
  `company_size_id` INT(10) UNSIGNED NOT NULL,
  `imgs` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '图集地址',
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `district_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `company_category_id` (`company_category_id` ASC),
  INDEX `company_status_id` (`company_status_id` ASC),
  INDEX `company_size_id` (`company_size_id` ASC),
  INDEX `district_id` (`district_id` ASC),
  CONSTRAINT `category_id`
    FOREIGN KEY (`company_category_id`)
    REFERENCES `zhaopin`.`company_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `company_size_id`
    FOREIGN KEY (`company_size_id`)
    REFERENCES `zhaopin`.`company_size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `company_status_id`
    FOREIGN KEY (`company_status_id`)
    REFERENCES `zhaopin`.`company_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `district_id`
    FOREIGN KEY (`district_id`)
    REFERENCES `zhaopin`.`districts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8
COMMENT = '企业';


-- -----------------------------------------------------
-- Table `zhaopin`.`credits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`credits` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`credits` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  `points` SMALLINT NOT NULL DEFAULT 0 COMMENT '分值',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '积分';


-- -----------------------------------------------------
-- Table `zhaopin`.`exp_companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`exp_companies` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`exp_companies` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(100) NOT NULL DEFAULT '',
  `started_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ended_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `content` VARCHAR(255) NOT NULL DEFAULT '',
  `company_category_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `company_category_id` (`company_category_id` ASC),
  CONSTRAINT `fk_exp_companies_company_categories`
    FOREIGN KEY (`company_category_id`)
    REFERENCES `zhaopin`.`company_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '工作经历公司';


-- -----------------------------------------------------
-- Table `zhaopin`.`experiences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`experiences` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`experiences` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '工作经历';


-- -----------------------------------------------------
-- Table `zhaopin`.`intentions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`intentions` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`intentions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '求职意向';


-- -----------------------------------------------------
-- Table `zhaopin`.`invites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`invites` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`invites` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '邀请';


-- -----------------------------------------------------
-- Table `zhaopin`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`migrations` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 38;


-- -----------------------------------------------------
-- Table `zhaopin`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`news` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`news` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '标题',
  `brief` VARCHAR(200) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '简述',
  `banner` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '缩略图',
  `keyword` VARCHAR(50) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT '' COMMENT '关键字',
  `content` LONGTEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '内容',
  `like_num` INT(11) NULL DEFAULT '0' COMMENT '点赞数',
  `read_num` INT(11) NULL DEFAULT '0' COMMENT '阅读量',
  `sort` INT(11) NULL DEFAULT '0' COMMENT '排序',
  `banner_status` ENUM('1', '2') COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT '1：上轮播，2：不上轮播',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `init_read_num` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '初始点击量',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 101;


-- -----------------------------------------------------
-- Table `zhaopin`.`notices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`notices` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`notices` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT '标题',
  `content` VARCHAR(300) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT '' COMMENT '内容',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4;


-- -----------------------------------------------------
-- Table `zhaopin`.`oauth_access_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`oauth_access_tokens` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`oauth_access_tokens` (
  `id` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `client_id` INT(11) NOT NULL,
  `name` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `scopes` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `oauth_access_tokens_user_id_index` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhaopin`.`oauth_auth_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`oauth_auth_codes` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`oauth_auth_codes` (
  `id` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_id` INT(11) NOT NULL,
  `client_id` INT(11) NOT NULL,
  `scopes` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhaopin`.`oauth_clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`oauth_clients` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`oauth_clients` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `secret` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `redirect` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `personal_access_client` TINYINT(1) NOT NULL,
  `password_client` TINYINT(1) NOT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `oauth_clients_user_id_index` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhaopin`.`oauth_personal_access_clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`oauth_personal_access_clients` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`oauth_personal_access_clients` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `oauth_personal_access_clients_client_id_index` (`client_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhaopin`.`oauth_refresh_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`oauth_refresh_tokens` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`oauth_refresh_tokens` (
  `id` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `access_token_id` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `oauth_refresh_tokens_access_token_id_index` (`access_token_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhaopin`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`password_resets` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`password_resets` (
  `email` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `token` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhaopin`.`salaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`salaries` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`salaries` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  `floor` DECIMAL(8,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '起薪',
  `ceil` DECIMAL(8,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '薪资上限',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = '工资';


-- -----------------------------------------------------
-- Table `zhaopin`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`positions` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`positions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  `keywords` VARCHAR(245) NOT NULL DEFAULT '',
  `room_and_board` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '管吃管住3、管吃1、管住2、不包0',
  `number` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '预招人数',
  `content` TEXT NOT NULL COMMENT '职位详情',
  `benefit` VARCHAR(245) NOT NULL DEFAULT '' COMMENT '福利待遇',
  `district_id` INT(10) UNSIGNED NOT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `salary_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `pd_district_id` (`district_id` ASC),
  INDEX `pc_company_id` (`company_id` ASC),
  INDEX `ps_salary_id` (`salary_id` ASC),
  CONSTRAINT `pc_company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `zhaopin`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pd_district_id`
    FOREIGN KEY (`district_id`)
    REFERENCES `zhaopin`.`districts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ps_salary_id`
    FOREIGN KEY (`salary_id`)
    REFERENCES `zhaopin`.`salaries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '职位';


-- -----------------------------------------------------
-- Table `zhaopin`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`users` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dealer_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `inviter_id` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '邀请人id',
  `sex` ENUM('1', '2') COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '性别：1：男 2：女',
  `address` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '地址',
  `name` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `tel` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `password` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `open_id` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `weChat_id` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `ticket` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `union_id` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `poster_id` VARCHAR(32) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `head_url` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1',
  `remember_token` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `points` INT NOT NULL DEFAULT 0 COMMENT '积分',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhaopin`.`resumes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`resumes` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`resumes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1' COMMENT '目前状态：在职1/离职0',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  `worked_at` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '参加工作时间',
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `fk_resumes_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zhaopin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '简历';


-- -----------------------------------------------------
-- Table `zhaopin`.`resume_has_exp_companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`resume_has_exp_companies` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`resume_has_exp_companies` (
  `resume_id` INT(10) UNSIGNED NOT NULL,
  `exp_company_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`resume_id`, `exp_company_id`),
  INDEX `exp_company_id` (`exp_company_id` ASC),
  INDEX `resume_id` (`resume_id` ASC),
  CONSTRAINT `fk_resumes_has_exp_companies_resumes1`
    FOREIGN KEY (`resume_id`)
    REFERENCES `zhaopin`.`resumes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resumes_has_exp_companies_exp_companies1`
    FOREIGN KEY (`exp_company_id`)
    REFERENCES `zhaopin`.`exp_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '简历和工作的公司关系表';


-- -----------------------------------------------------
-- Table `zhaopin`.`resume_has_positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`resume_has_positions` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`resume_has_positions` (
  `resume_id` INT(10) UNSIGNED NOT NULL,
  `position_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`resume_id`, `position_id`),
  INDEX `position_id` (`position_id` ASC),
  INDEX `resume_id` (`resume_id` ASC),
  CONSTRAINT `fk_resumes_has_positions_resumes1`
    FOREIGN KEY (`resume_id`)
    REFERENCES `zhaopin`.`resumes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resumes_has_positions_positions1`
    FOREIGN KEY (`position_id`)
    REFERENCES `zhaopin`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zhaopin`.`user_has_credits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`user_has_credits` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`user_has_credits` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `credit_id` INT(10) UNSIGNED NOT NULL COMMENT '积分ID 为0时为积分兑换现金',
  `points` SMALLINT NOT NULL DEFAULT 0,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0兑换中\n1兑换成功\n2兑换失败',
  `remark` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '备注',
  INDEX `credit_id` (`credit_id` ASC),
  INDEX `user_id` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_has_credits_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `zhaopin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_credits_credits1`
    FOREIGN KEY (`credit_id`)
    REFERENCES `zhaopin`.`credits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
