-- MySQL Script generated by MySQL Workbench
-- 2018年07月02日 星期一 17时26分47秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zhaopin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zhaopin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zhaopin` DEFAULT CHARACTER SET utf8mb4 ;
USE `zhaopin` ;

-- -----------------------------------------------------
-- Table `zhaopin`.`company_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`company_categories` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`company_categories` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = '行业';


-- -----------------------------------------------------
-- Table `zhaopin`.`company_size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`company_size` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`company_size` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `sort` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `min` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `max` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COMMENT = '企业规模';


-- -----------------------------------------------------
-- Table `zhaopin`.`company_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`company_status` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`company_status` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = '公司状态';


-- -----------------------------------------------------
-- Table `zhaopin`.`districts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`districts` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`districts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  `parent_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `parent_id` (`parent_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COMMENT = '地区';


-- -----------------------------------------------------
-- Table `zhaopin`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`companies` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`companies` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `logo` VARCHAR(245) NOT NULL DEFAULT '',
  `number` VARCHAR(245) NOT NULL DEFAULT '' COMMENT '企业人数',
  `profile` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '公司简介',
  `phone` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '商务电话',
  `wechat` VARCHAR(45) NOT NULL DEFAULT '',
  `qq` VARCHAR(45) NOT NULL DEFAULT '',
  `company_category_id` INT(10) UNSIGNED NOT NULL COMMENT '行业id',
  `company_status_id` INT(10) UNSIGNED NOT NULL,
  `company_size_id` INT(10) UNSIGNED NOT NULL,
  `imgs` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '图集地址',
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `district_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `company_category_id` (`company_category_id` ASC),
  INDEX `company_status_id` (`company_status_id` ASC),
  INDEX `company_size_id` (`company_size_id` ASC),
  INDEX `district_id` (`district_id` ASC),
  CONSTRAINT `category_id`
    FOREIGN KEY (`company_category_id`)
    REFERENCES `zhaopin`.`company_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `company_size_id`
    FOREIGN KEY (`company_size_id`)
    REFERENCES `zhaopin`.`company_size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `company_status_id`
    FOREIGN KEY (`company_status_id`)
    REFERENCES `zhaopin`.`company_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `district_id`
    FOREIGN KEY (`district_id`)
    REFERENCES `zhaopin`.`districts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8
COMMENT = '企业';


-- -----------------------------------------------------
-- Table `zhaopin`.`credit_configs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`credit_configs` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`credit_configs` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  `points` SMALLINT NOT NULL DEFAULT 0 COMMENT '分值',
  `max` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0不限制\n大于0可获取N次',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '积分配置';


-- -----------------------------------------------------
-- Table `zhaopin`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`users` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dealer_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `inviter_id` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '邀请人id',
  `sex` ENUM('1', '2') COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '性别：1：男 2：女',
  `address` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '地址',
  `name` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `tel` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `password` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `open_id` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `weChat_id` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `ticket` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `union_id` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `poster_id` VARCHAR(32) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `head_url` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1',
  `remember_token` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `points` INT NOT NULL DEFAULT 0 COMMENT '积分',
  `mobile` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhaopin`.`resumes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`resumes` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`resumes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `gender` VARCHAR(45) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1' COMMENT '目前状态：在职1/离职0',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  `worked_at` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '参加工作时间',
  `user_id` INT(10) UNSIGNED NOT NULL,
  `age` VARCHAR(45) NOT NULL DEFAULT '',
  `city` VARCHAR(45) NOT NULL DEFAULT '',
  `intentions_name` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '求职意向',
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `fk_resumes_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zhaopin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '简历';


-- -----------------------------------------------------
-- Table `zhaopin`.`experiences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`experiences` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`experiences` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(245) NOT NULL DEFAULT '',
  `category_name` VARCHAR(20) NOT NULL DEFAULT '',
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `started_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `ended_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `resume_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `resume_id` (`resume_id` ASC),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `er_resume_id`
    FOREIGN KEY (`resume_id`)
    REFERENCES `zhaopin`.`resumes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ue_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `zhaopin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '工作经历';


-- -----------------------------------------------------
-- Table `zhaopin`.`intentions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`intentions` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`intentions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '求职意向';


-- -----------------------------------------------------
-- Table `zhaopin`.`invites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`invites` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`invites` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '邀请';


-- -----------------------------------------------------
-- Table `zhaopin`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`news` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`news` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '标题',
  `brief` VARCHAR(200) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '简述',
  `banner` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '缩略图',
  `keyword` VARCHAR(50) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT '' COMMENT '关键字',
  `content` LONGTEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '内容',
  `like_num` INT(11) NULL DEFAULT '0' COMMENT '点赞数',
  `read_num` INT(11) NULL DEFAULT '0' COMMENT '阅读量',
  `sort` INT(11) NULL DEFAULT '0' COMMENT '排序',
  `banner_status` ENUM('1', '2') COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT '1：上轮播，2：不上轮播',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `init_read_num` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '初始点击量',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 101;


-- -----------------------------------------------------
-- Table `zhaopin`.`notices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`notices` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`notices` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT '标题',
  `content` VARCHAR(300) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT '' COMMENT '内容',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4;


-- -----------------------------------------------------
-- Table `zhaopin`.`salaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`salaries` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`salaries` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  `floor` DECIMAL(8,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '起薪',
  `ceil` DECIMAL(8,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '薪资上限',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = '工资';


-- -----------------------------------------------------
-- Table `zhaopin`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`positions` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`positions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sort` SMALLINT(6) NOT NULL DEFAULT '0',
  `keywords` VARCHAR(245) NOT NULL DEFAULT '',
  `room_and_board` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '管吃管住3、管吃1、管住2、不包0',
  `number` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '预招人数',
  `content` TEXT NOT NULL COMMENT '职位详情',
  `benefit` VARCHAR(245) NOT NULL DEFAULT '' COMMENT '福利待遇',
  `district_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `company_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `salary_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `pd_district_id` (`district_id` ASC),
  INDEX `pc_company_id` (`company_id` ASC),
  INDEX `ps_salary_id` (`salary_id` ASC),
  CONSTRAINT `pc_company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `zhaopin`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pd_district_id`
    FOREIGN KEY (`district_id`)
    REFERENCES `zhaopin`.`districts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ps_salary_id`
    FOREIGN KEY (`salary_id`)
    REFERENCES `zhaopin`.`salaries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '职位';


-- -----------------------------------------------------
-- Table `zhaopin`.`user_points_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`user_points_logs` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`user_points_logs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `credit_config_id` INT(10) UNSIGNED NOT NULL COMMENT '积分ID 为0时为积分兑换现金',
  `points` SMALLINT NOT NULL DEFAULT 0,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0兑换中\n1兑换成功\n2兑换失败',
  `remark` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '备注',
  `code` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '识别码表名+id\nposition_id\nnews_id',
  INDEX `credit_config_id` (`credit_config_id` ASC),
  INDEX `user_id` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_up_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `zhaopin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_up_credit_config_id`
    FOREIGN KEY (`credit_config_id`)
    REFERENCES `zhaopin`.`credit_configs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户积分变动记录表';


-- -----------------------------------------------------
-- Table `zhaopin`.`user_has_positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`user_has_positions` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`user_has_positions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `position_id` INT(10) UNSIGNED NOT NULL,
  `resume_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `up_position_id` (`position_id` ASC),
  INDEX `uhp_user_id` (`user_id` ASC),
  INDEX `uhp_resume_id` (`resume_id` ASC),
  CONSTRAINT `uhp_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `zhaopin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `up_position_id`
    FOREIGN KEY (`position_id`)
    REFERENCES `zhaopin`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `uhp_resume_id`
    FOREIGN KEY (`resume_id`)
    REFERENCES `zhaopin`.`resumes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户投递简历表';


-- -----------------------------------------------------
-- Table `zhaopin`.`codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhaopin`.`codes` ;

CREATE TABLE IF NOT EXISTS `zhaopin`.`codes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mobile` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `code` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `type_name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `expired` INT UNSIGNED NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
